### ISSUE TITLE
Dashboard shows blank page when opening Roles window with Menus plugin enabled

### ISSUE THREAD

**Issue by lowercasename** [mattmilburn/strapi-plugin-menus#92] opened 2023-03-02 09:16 UTC
Hi, I've tested a clean install of Strapi 4.7.0 with this plugin and once the plugin is installed, this issue comes up: https://github.com/strapi/strapi/issues/15961.

Not surprising as you don't claim compatibility with 4.7.x, but just a heads up!

**Comment by mikegazdag** [comment] 2023-03-04 00:49
Confirmed behaviour!

**Comment by jwalcher** [comment] 2023-03-05 19:27
the issue starts with 4.6.2, I'm stuck at 4.6.1 for this reason

**Comment by darokviana** [comment] 2023-03-07 12:10
I updated my Strapi version to 4.7.1 and faced the same issue.

**Comment by everythinginjs** [comment] 2023-03-10 18:03
@mattmilburn  found the issue it is because of dependency tree for match-sorter package. look to the issue [#16028](https://github.com/strapi/strapi/issues/16028) I added below to my package.json but did not fix it.
```
  "resolutions": {
    "match-sorter": "6.0.2"
  },
```

**Comment by everythinginjs** [comment] 2023-03-10 19:57
for now, below one does work for the following env:
strapi version: 4.7.1
strapi-plugin-menus: 1.3.1

just add it to your strapi package.json.
```
  "resolutions": {
    "match-sorter": "6.3.1"
  },
```
if it did not work run yarn build command.
no need any patch package.

**Comment by mattmilburn** [comment] 2023-03-10 20:19
@everythinginjs It seems that v4.7x requires the 6.3.1 version of `match-sorter` and @jwalcher v4.6x requires the 4.2.1 version of `match-sorter` like in the example above for your Strapi application.

Now, can this be provided directly in the plugin? 🤔

**Comment by ARA1985** [comment] 2023-03-10 21:19
Hi, i have configuration:
strapi version: 4.7.1
strapi-plugin-menus: 1.3.1

I add to my strapi package.json:
` "resolutions": {
    "match-sorter": "6.3.1"
  },`
  
  But it doesn't help. I remove node_module folder and yarn install from scratch. I saw the line in the console:
`  warning Resolution field "match-sorter@6.3.1" is incompatible with requested version "match-sorter@^4.0.2"`

**Comment by mattmilburn** [comment] 2023-03-10 21:44
Hmmm @everythinginjs seems like I can now only get this fix to work with Strapi v4.6.2.

But you say the same fix is working for you when using Strapi v4.7.1 and `match-sorter` v6.3.1?

**Comment by rihards-simanovics** [comment] 2023-03-10 22:03
There is a chance that I did something wrong, but the fix proposed by the @everythinginjs is not working for me, despite me having the same env as them. I am getting a similar message to @ARA1985
> yarn
> yarn install v1.22.19
> [1/5] Validating package.json...
> [2/5] Resolving packages...
> warning Resolution field "match-sorter@6.3.1" is incompatible with requested version "match-sorter@^4.0.2"
> success Already up-to-date.
> Done in 0.52s.

Is it possible that I'm doing something wrong?

**Comment by mattmilburn** [comment] 2023-03-10 22:07
@rihards-simanovics @ARA1985 I'm having the same problem with Strapi v4.7 and the menus plugin. Sorru, still working on a solution 🤔

**Comment by rihards-simanovics** [comment] 2023-03-10 22:09
@mattmilburn no worries, I have recently moved from WP, and just getting to know the platform so no in a great rush, so just will disable the plugin for the time being.

**Comment by everythinginjs** [comment] 2023-03-11 06:38
@mattmilburn strange since it is working for me with the config that I mentioned, I believe that for the alternative way others should use patch package and add proper version of match-sorter in strapi-plugin-permissions.

**Comment by everythinginjs** [comment] 2023-03-15 19:04
Hey @mattmilburn , strapi 4.8.0 has been released and fixed this bug I think you can close this issue.

**Comment by rihards-simanovics** [comment] 2023-03-16 09:09
> Hey @mattmilburn , strapi 4.8.0 has been released and fixed this bug I think you can close this issue.

Hey nice! let me give it a try on my system.

**Comment by rihards-simanovics** [comment] 2023-03-16 09:48
Can confirm that it works now

**Comment by mattmilburn** [comment] 2023-03-21 21:49
@everythinginjs @rihards-simanovics Also confirming that v4.8x resolves this issue 👍🏻

**Closed by mattmilburn** 2023-03-21 21:49 UTC
Labels: bug
